/**
 * Test script for /api/resume/select endpoint
 *
 * Usage: tsx scripts/test-bullet-selection-api.ts [roleProfileId]
 *
 * Examples:
 * tsx scripts/test-bullet-selection-api.ts developer-relations-lead
 * tsx scripts/test-bullet-selection-api.ts web3-blockchain-lead
 */

const API_URL = 'http://localhost:3000/api/resume/select'

// Mock Turnstile token for local testing
// In production, this would be generated by Cloudflare widget
const MOCK_TURNSTILE_TOKEN = 'test-token-for-local-dev'

async function testBulletSelection(roleProfileId: string) {
  console.log(`\n🎯 Testing bullet selection for role: ${roleProfileId}\n`)

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        roleProfileId,
        turnstileToken: MOCK_TURNSTILE_TOKEN,
        config: {
          maxBullets: 18,
          maxPerCompany: 6,
          maxPerPosition: 4,
        },
      }),
    })

    const data = await response.json()

    if (!response.ok) {
      console.error(`❌ API Error (${response.status}):`, data.error)
      if (data.message) console.error(`   ${data.message}`)
      return
    }

    console.log(`✅ Success! Selected ${data.count} bullets\n`)

    console.log('📊 Role Profile:')
    console.log(`   ID: ${data.roleProfile.id}`)
    console.log(`   Name: ${data.roleProfile.name}`)
    console.log(`   Description: ${data.roleProfile.description}\n`)

    console.log('⚙️  Selection Config:')
    console.log(`   Max bullets: ${data.config.maxBullets}`)
    console.log(`   Max per company: ${data.config.maxPerCompany}`)
    console.log(`   Max per position: ${data.config.maxPerPosition}\n`)

    console.log('📋 Top 10 Selected Bullets:\n')

    const top10 = data.selected.slice(0, 10)
    for (let i = 0; i < top10.length; i++) {
      const item = top10[i]
      console.log(`${i + 1}. [Score: ${item.score.toFixed(3)}]`)
      console.log(`   Company: ${item.companyName}`)
      console.log(`   Position: ${item.positionRole}`)
      console.log(`   Bullet: ${item.bullet.text.substring(0, 100)}...`)
      console.log(
        `   Tags: ${item.bullet.tags.length > 0 ? item.bullet.tags.join(', ') : '(none)'}`
      )
      console.log(`   Priority: ${item.bullet.priority}/10\n`)
    }

    // Summary statistics
    const companyCounts: Record<string, number> = {}
    const positionCounts: Record<string, number> = {}

    for (const item of data.selected) {
      companyCounts[item.companyId] = (companyCounts[item.companyId] || 0) + 1
      positionCounts[item.positionId] =
        (positionCounts[item.positionId] || 0) + 1
    }

    console.log('📈 Diversity Statistics:')
    console.log(
      `   Companies represented: ${Object.keys(companyCounts).length}`
    )
    console.log(
      `   Positions represented: ${Object.keys(positionCounts).length}`
    )
    console.log(
      `   Avg bullets per company: ${(data.count / Object.keys(companyCounts).length).toFixed(1)}`
    )
    console.log(
      `   Avg bullets per position: ${(data.count / Object.keys(positionCounts).length).toFixed(1)}\n`
    )

    // Rate limit info
    console.log('🚦 Rate Limit Info:')
    const headers = response.headers
    console.log(`   Limit: ${headers.get('X-RateLimit-Limit')} per hour`)
    console.log(`   Remaining: ${headers.get('X-RateLimit-Remaining')}`)
    console.log(`   Resets: ${headers.get('X-RateLimit-Reset')}\n`)
  } catch (error) {
    console.error('❌ Request failed:', error)
  }
}

// Get role profile from command line or use default
const roleProfileId = process.argv[2] || 'developer-relations-lead'

// Available role profiles for reference
const availableProfiles = [
  'developer-relations-lead',
  'web3-blockchain-lead',
  'ai-ml-product-lead',
  'technical-product-manager',
  'growth-technical-leader',
  'head-of-community-ecosystem',
]

console.log('\n📚 Available role profiles:')
for (const profile of availableProfiles) {
  console.log(`   - ${profile}`)
}

testBulletSelection(roleProfileId)
