#!/usr/bin/env bash
# Parses test logs and updates METRICS.md
# Called automatically by 'just test' - NO TEST EXECUTION HERE

set -euo pipefail

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M")
if date -v+1d &>/dev/null 2>&1; then
  EXPIRY=$(date -u -v+1d +"%Y-%m-%dT%H:%M")
else
  EXPIRY=$(date -u -d "+1 day" +"%Y-%m-%dT%H:%M")
fi

# Temp log files (written by justfile)
RUST_LOG="/tmp/resumate-rust-tests.log"
TS_LOG="/tmp/resumate-ts-tests.log"

# Verify logs exist
if [[ ! -f "$RUST_LOG" ]]; then
  echo "❌ Rust test log not found: $RUST_LOG"
  echo "   Run 'just test' to generate logs"
  exit 1
fi

if [[ ! -f "$TS_LOG" ]]; then
  echo "❌ TypeScript test log not found: $TS_LOG"
  echo "   Run 'just test' to generate logs"
  exit 1
fi

echo "📊 Parsing test logs to generate METRICS.md..."

# Parse Rust tests (sum all "X passed" from multiple test suites)
RUST_COUNT=$(grep -E "test result: ok\." "$RUST_LOG" | grep -oE "[0-9]+ passed" | grep -oE "[0-9]+" | awk '{sum+=$1} END {print sum}')
RUST_COUNT=${RUST_COUNT:-0}
RUST_IGNORED=$(grep -E "test result: ok\." "$RUST_LOG" | grep -oE "[0-9]+ ignored" | grep -oE "[0-9]+" | awk '{sum+=$1} END {print sum}')
RUST_IGNORED=${RUST_IGNORED:-0}

# Parse TypeScript tests (use summary line "Tests  200 passed (200)")
TS_COUNT=$(grep -E "Tests.*passed" "$TS_LOG" | grep -oE "[0-9]+ passed" | head -1 | grep -oE "[0-9]+" || echo "0")
TS_COUNT=${TS_COUNT:-0}

TOTAL_COUNT=$((RUST_COUNT + TS_COUNT))

# Extract timing from duration lines
RUST_TIME=$(grep -E "finished in [0-9]+\.[0-9]+s" "$RUST_LOG" | grep -oE "[0-9]+\.[0-9]+s" | sed 's/s//' | awk '{sum+=$1} END {printf "%.2fs", sum}')
RUST_TIME=${RUST_TIME:-N/A}
TS_TIME=$(grep "Duration" "$TS_LOG" | grep -oE "[0-9]+\.[0-9]+s" | head -1 || echo "N/A")

# Skip per-crate breakdown for simplicity (would require complex parsing)
# Users can inspect the full log file for detailed per-crate information
CORE_TESTS="See log"
TYPST_TESTS="See log"
WASM_TESTS="See log"
SHARED_TESTS="See log"

# Get TypeScript breakdown (count tests per file)
TS_FILE_COUNT=$(grep -cE "✓.*\([0-9]+ tests\)" "$TS_LOG" || echo "0")

# Get coverage if llvm-cov is installed
if command -v cargo-llvm-cov &>/dev/null; then
  RUST_COVERAGE=$(cargo llvm-cov --workspace --summary-only 2>&1 | grep -E "TOTAL" | awk '{print $10}' || echo "Not available")
else
  RUST_COVERAGE="Not installed (cargo install cargo-llvm-cov)"
fi

# Generate METRICS.md
cat > docs/METRICS.md <<EOF
---
Generated: $TIMESTAMP
Generator: scripts/update-metrics-from-logs.sh
Source: Parsed from test execution logs
Valid Until: $EXPIRY (24h expiry)
---

# Project Metrics (Auto-Generated)

**⚠️ DO NOT EDIT THIS FILE MANUALLY**
This file is automatically updated when you run \`just test\`
To update: Run \`just test\` again

---

## Test Counts

### Summary

| Language | Tests | Ignored | Time | Status |
|----------|-------|---------|------|--------|
| **Rust** | $RUST_COUNT | $RUST_IGNORED | $RUST_TIME | ✅ Passing |
| **TypeScript** | $TS_COUNT | 0 | $TS_TIME | ✅ Passing |
| **TOTAL** | **$TOTAL_COUNT** | **$RUST_IGNORED** | $RUST_TIME + $TS_TIME | ✅ All Passing |

### Rust Tests (By Crate)

| Crate | Tests | Notes |
|-------|-------|-------|
| docgen-core | $CORE_TESTS | Scoring, selection, validation |
| docgen-typst | $TYPST_TESTS | PDF generation, Typst rendering |
| docgen-wasm | $WASM_TESTS | WASM bindings, JS interop |
| shared-types | $SHARED_TESTS | Type validation, schema |
| **Total** | **$RUST_COUNT** | All Rust tests |

### TypeScript Tests

| Metric | Value |
|--------|-------|
| Total Tests | $TS_COUNT |
| Test Files | $TS_FILE_COUNT |
| Execution Time | $TS_TIME |

**Test files breakdown available in log:** \`$TS_LOG\`

---

## Coverage

### Rust Coverage

**Line Coverage:** $RUST_COVERAGE

**Command to generate detailed report:**
\`\`\`bash
just coverage-rust        # Generate HTML report
just coverage-rust-open   # Open in browser
\`\`\`

**Last coverage snapshot:** See docs/TESTING_INFRASTRUCTURE_ANALYSIS.md for detailed breakdown

### TypeScript Coverage

**Command to generate detailed report:**
\`\`\`bash
just coverage-ts          # Generate HTML report
just coverage-ts-open     # Open in browser
\`\`\`

---

## Test Execution Details

**Rust Tests:**
- Command: \`cargo test --all\`
- Log: \`$RUST_LOG\`
- Duration: $RUST_TIME
- Suites: Multiple (core, typst, wasm, shared-types, integration, doc-tests)

**TypeScript Tests:**
- Command: \`bun run test --run\`
- Log: \`$TS_LOG\`
- Duration: $TS_TIME
- Files: $TS_FILE_COUNT test files

---

## Commands

**Run all tests:**
\`\`\`bash
just test              # Runs tests and updates this file
just test-rust         # Rust only
just test-ts           # TypeScript only
\`\`\`

**Coverage reports:**
\`\`\`bash
just coverage          # Generate both Rust + TypeScript
just coverage-rust     # Rust coverage report
just coverage-ts       # TypeScript coverage report
\`\`\`

**View logs:**
\`\`\`bash
cat $RUST_LOG     # View Rust test output
cat $TS_LOG       # View TypeScript test output
\`\`\`

---

## Verification

**Last Generated:** $TIMESTAMP
**Next Update:** Automatically on next \`just test\` run
**Logs Valid For:** Current session (stored in /tmp)

**To verify counts:**
\`\`\`bash
# Check Rust
grep "test result: ok" $RUST_LOG | grep -oE "[0-9]+ passed"

# Check TypeScript
grep "Tests.*passed" $TS_LOG
\`\`\`

---

*This file is auto-generated from test execution logs.*
*For testing strategy and philosophy, see: docs/TESTING_STRATEGY.md*
*For current project phase and status, see: docs/CURRENT_PHASE.md*
EOF

echo "✅ METRICS.md generated at $TIMESTAMP"
echo ""
echo "📊 Test Summary:"
echo "   Rust:       $RUST_COUNT tests (${RUST_IGNORED} ignored) in $RUST_TIME"
echo "   TypeScript: $TS_COUNT tests in $TS_TIME"
echo "   Total:      $TOTAL_COUNT tests"
echo ""
echo "📍 Location: docs/METRICS.md"
echo "⏰ Valid until: $EXPIRY"
